### PR TITLE
Gradle script

### PR DESCRIPTION
**Pull request by adamarla**
Script for equivalent gradle build

### CODE REVIEW

**Comment by hpgrahsl** [comment]
@adamarla awesome! many thx for providing this basic gradle build support. ran it locally and seems to be fine. question is does it build a JAR with dependencies as well? I thought it should but couldn't find one after wiping out the target folder with mvn clean first and then running gradle build. also the integration test is skipped by default and the flag needs to be explicitly set to true in the build.gradle file, right? I assume this is because it locally fails for you have to check myself what's going on there.

**Comment by adamarla** [comment]
Hi @hpgrahsl - 

> question is does it build a JAR with dependencies as well? 

It does build an "uberjar" with dependencies. But for that you have to use the task `gradle shadowJar` which uses the excellent [shadow jar](https://github.com/johnrengelman/shadow) project.

> Integration test is skipped by default and the flag needs to be explicitly set to true in the build.gradle file, right? I assume this is because it locally fails for you

Yes, this is correct. Unfortunately I have not been able to get to the bottom of this. Everything works correctly till [here](https://github.com/RunTitle/kafka-connect-mongodb/blob/27a6c0a8c919e0b07485b662da3ef516af3be3e8/src/test/java/at/grahsl/kafka/connect/mongodb/end2end/MinimumViableIT.java#L149l). But after the subsequent delay, I see no records in the mongo collection and no error either. If it works for you locally, you should change it to default _true_ for integration tests.

**Comment by hpgrahsl** [comment]
I see. Looks good to me. Will check later what might be wrong with the integration tests for gradle. About to merge it. Many THX again!

**Comment by hpgrahsl** [comment]
@adamarla just found the issue. wasn't too hard to find. the problem seems to be that for the gradle build the 'uberjar' doesn't land in the target folder. then mounting this volume in the docker compose file doesn't provide the needed build artifact to the kafka connect service which then of course fails.

however, if the `target/` folder is pre-created manually and I run `gradle copyJarToTarget` followed by `gradle test` it works for me.

should be an easy fix!

**Comment by adamarla** [comment]
@hpgrahsl - I think this can be handled as a documentation fix. The simplest (and most appropriate i think) solution would be to rename `copyJarToTarget` task to something like `distribute` (or something similar) and then document `gradle distribute` as the default action to take. This will guarantee that all the prior steps including creation of `target` folder are handled automatically. 

What do you think?

**Pull request merged**
